### PR TITLE
Updated nlopt

### PR DESCRIPTION
**Pull request by eggerk**
This should fix multiagent_mapping builds on xenial docker slaves. See https://github.com/ethz-asl/cmvs_pmvs_catkin/pull/7 and https://github.com/ethz-asl/nlopt/issues/8

Alternative, better fix than #101

@HannesSommer

### CODE REVIEW

**Comment by HannesSommer** [comment]
Arrrg, OSX fails, but most likely unrelatedly. @eggerk , do you agree on that?

**Comment by eggerk** [comment]
The failure here is because cv_bridge is broken on OSX for some reason: http://129.132.38.183:8080/job/vision_opencv/5/

**Comment by HannesSommer** [comment]
Thanks, then this lgtm.

**Comment by eggerk** [comment]
Thanks to the help of @HannesSommer, multiagent_mapping now properly compiles on xenial docker slaves.

@dymczykm I'd suggest we enable testing on xenial for subtree_multiagent_mapping

**Pull request merged**
