### PR TITLE
updated glags. Necessary for kinetic.

### PR DESCRIPTION
**Pull request by alexmillane**
Updated gflags to include gflags commit

https://github.com/ethz-asl/gflags_catkin/commit/8aa84ac014d512a5e71c8d9035e539716e2c8186

Necissary for compilation in kinetic.

### CODE REVIEW

**Comment by alexmillane** [comment]
@helenol @schneith

**Comment by alexmillane** [comment]
And yes im retarded enough to try kinetic.

**Comment by helenol** [comment]
add to whitelist

**Comment by helenol** [comment]
add to whitelist (as admin this time)

**Comment by helenol** [comment]
LGTM

**Pull request merged**
