### PR TITLE
Reenable CMVS

### PR DESCRIPTION
**Pull request by mfehr**

### CODE REVIEW

**Comment by simonlynen** [comment]
ok to test

**Comment by mfehr** [comment]
test this please

**Comment by mfehr** [comment]
test this please

**Comment by mfehr** [comment]
test this please

**Comment by mfehr** [comment]
test this please

**Comment by simonlynen** [comment]
add to whitelist.

**Comment by simonlynen** [comment]
Lgtm

**Comment by mfehr** [comment]
test this please

**Comment by mfehr** [comment]
retest this please

**Comment by mfehr** [comment]
retest this please

**Comment by mfehr** [comment]
retest this please

**Comment by mfehr** [comment]
Waiting for this PR: https://github.com/ethz-asl/cmvs_pmvs_catkin/pull/4

**Pull request merged**
