### PR TITLE
move to newest pmvs commit

### PR DESCRIPTION
**Pull request by mfehr**
the previous move was one commit short.

### CODE REVIEW

**Comment by simonlynen** [comment]
ok to test

**Comment by simonlynen** [comment]
lgtm

**Comment by mfehr** [comment]
retest this please

**Comment by mfehr** [comment]
test this please

**Comment by mfehr** [comment]
retest this please

**Comment by simonlynen** [comment]
Add to whitelist

**Comment by simonlynen** [comment]
test this please

**Comment by mfehr** [comment]
retest this please

**Pull request merged**
