### PR TITLE
Update to use system Eigen

### PR DESCRIPTION
**Pull request by eggerk**
Needs to build:
- [x] thirdparty
- [x] MapLabMultiarch
- [x] ~~MuMa Multiarch~~

To be reviewed:
- [x] This PR
- [x] ceres
- [x] ~~eigen_catkin~~
- [x] ~~aslam basic~~
- [x] MapLab
- [x] ~~MuMa~~
- [ ] Clean up aslam_install

### CODE REVIEW

**Comment by fabianbl** [comment]
@eggerk Can we merge this now?

**Comment by eggerk** [comment]
@fabianbl Did you have a successful multiarch build? If so, this should be good to merge

@mfehr @schneith any objections to merging this?

**Comment by fabianbl** [comment]
@eggerk @mfehr @schneith Last week's multiarch build was successful, I will do another try now to be sure: http://129.132.38.183:8080/view/maplab/job/maplab_multiarch/145/

**Comment by eggerk** [comment]
For some reasons Jenkins failed checking out this repo. I updated the rosinstall: https://github.com/ethz-asl/aslam_install/pull/117 Hopefully, this will fix it

**Comment by fabianbl** [comment]
Next try: http://129.132.38.183:8080/view/maplab/job/maplab_multiarch/147/

**Comment by fabianbl** [comment]
http://129.132.38.183:8080/view/maplab/job/maplab_multiarch/149/

**Comment by fabianbl** [comment]
@eggerk @mfehr @schneith All builds working fine now, I think we can merge this.

**Pull request merged**
