### PR TITLE
Updated opencv URL

### PR DESCRIPTION
**Pull request by dymczykm**
Current opencv master

### CODE REVIEW

**Comment by dymczykm** [comment]
test this please

**Comment by dymczykm** [comment]
test this please

**Comment by schneith** [comment]
test this please

**Comment by schneith** [comment]
This build probably fails because of an old version of gtsam that is downloaded per default in the gtsam_catkin package and fails to build on osx. If no one depends on this old version we could update it to the most recent develop branch of upstream gtsam.

**Comment by markusachtelik** [comment]
Fine for me

On Jul 18, 2015 11:20 AM, Thomas Schneider <notifications@github.com> wrote:

This build probably fails because of an old version of gtsam that is downloaded per default in the gtsam_catkin package and fails to build on osx. If no one depends on this old version we could update it to the most recent develop branch of upstream gtsam.

**Pull request closed without merging**
