### PR TITLE
Remove qhull

### PR DESCRIPTION
**Pull request by dymczykm**
Build fails on osx.

### CODE REVIEW

**Comment by dymczykm** [comment]
test this please

**Comment by tcies** [comment]
lgtm :disappointed:

**Comment by dymczykm** [comment]
test this please

**Comment by dymczykm** [comment]
Build passes on ubuntu jenkins, osx currently down

**Comment by dymczykm** [comment]
test this please

**Comment by dymczykm** [comment]
test this please

**Pull request merged**
