### PR TITLE
Readd gurobi

### PR DESCRIPTION
**Pull request by simonlynen**

### CODE REVIEW

**Comment by dymczykm** [comment]
Then i'll delete it from the install manual (added as a separate pkg to be gitcloned)

**Comment by dymczykm** [comment]
and lgtm

**Comment by simonlynen** [comment]
no need, @helenol already did this which is why builds started failing
since somehow gurobi got dropped from thirdparty again

**Comment by simonlynen** [comment]
test this please

**Comment by markusachtelik** [comment]
Is it freely available now?

From: Simon Lynen
Reply-To: ethz-asl/thirdparty_submodules
Date: Monday 23 March 2015 23:28
To: ethz-asl/thirdparty_submodules
Subject: Re: [thirdparty_submodules] Readd gurobi (#59)


Merged #59<https://github.com/ethz-asl/thirdparty_submodules/pull/59>.

**Comment by helenol** [comment]
Ah crap this is really my bad - thought we had decided to move it TO thirdparty submodules?
Looking at my ws now, looks like wstool update just leaves gurobi_catkin as untracked when it was removed 2 weeks ago.
Really sorry about this!

**Comment by helenol** [comment]
@markusachtelik, @simonlynen, @dymczykm Actually reading all the package descriptions again, gurobi_catkin got moved out because it's under private academic license, right? So it really doesn't belong in thirdparty and I messed up. We should revert this change and I'll fix my PR removing gurobi from map_api.rosinstall.
Again, super sorry about this!

**Pull request merged**
