### PR TITLE
protobuffer updated to version 2.6.1

### PR DESCRIPTION
**Pull request by ffurrer**

### CODE REVIEW

**Comment by simonlynen** [comment]
**DON'T MERGE**

**Comment by simonlynen** [comment]
test this pleast

**Comment by simonlynen** [comment]
ok to test

**Comment by simonlynen** [comment]
test this please

**Comment by ffurrer** [comment]
test this please

**Comment by simonlynen** [comment]
Add to whitelist.

**Comment by simonlynen** [comment]
test this please

**Comment by schneith** [comment]
What is the problem with the upgrade?

**Comment by ffurrer** [comment]
I don't know, @tcies, @simonlynen, did you resolve the issue?

**Comment by simonlynen** [comment]
@schneith this breaks map-api tests.

**Comment by tcies** [comment]
I'm merging this. Apart from the need to rm old protobuf generated headers and sources, map_api and viba unit tests work, as does loading in, visualizing and checking consistency of an old map.

**Comment by tcies** [comment]
(this update seems to speed things up, and we need speed right now)

**Comment by tcies** [comment]
Will send out an e-mail with instructions on proto deleting to the muma mailing list.

**Comment by tcies** [comment]
Actually, let me run a multiarch build first...

**Comment by tcies** [comment]
Ooops, breaks some tango loader test. Will tal asap.

**Comment by tcies** [comment]
This is incompatible with the precompiled tango libs. :(

**Comment by simonlynen** [comment]
If you need help with updating these write me a mail

**Comment by tcies** [comment]
mail sent, thanks!

**Pull request merged**
