### PR TITLE
changed zeromq url to working one

### PR DESCRIPTION
**Pull request by ZacharyTaylor**
zeromq's url has changed. This update switches it to the new one 
see https://github.com/ethz-asl/zeromq_catkin/pull/8

### CODE REVIEW

**Comment by dymczykm** [comment]
add to whitelist

**Comment by schneith** [comment]
lgtm

**Comment by dymczykm** [comment]
```
CMake Error at zeromq_src-stamp/download-zeromq_src.cmake:9 (file):
  file DOWNLOAD HASH mismatch
    for file: [/home/jenkins/workspace/thirdparty_submodules_multiarch/label/ubuntu/build/zeromq_catkin/zeromq_src-prefix/src/zeromq-4.0.7.tar.gz]
      expected hash: [9b46f7e7b0704b83638ef0d461fd59ab]
        actual hash: [d41d8cd98f00b204e9800998ecf8427e]
```

**Comment by hitimo** [comment]
test this please

**Comment by schneith** [comment]
Jenkins is dead :(

**Comment by schneith** [comment]
test this please

**Comment by schneith** [comment]
test this please

**Comment by schneith** [comment]
test this please?

**Comment by schneith** [comment]
test this please

**Comment by schneith** [comment]
test this please

**Pull request closed without merging**
